### ISSUE TITLE
Burp Suite v2022.3.7では動きませんでした

### ISSUE THREAD

**Issue by irok** [ankokuty/HakoniwaBadStore#1]
社内のハンズオンで使わせて頂いています。
Burp Suite Community Edition v2021.12.1 を使っていたときは動いていたのですが、同 v2022.3.7 では「Stopped」ボタンを押すと

> failed to create a new resolver

というエラーが表示されて起動しませんでした。
※上記バージョンの間にもいくつか更新があったようですが、どこから動かなくなったのかは分かりませんでした。
※新しく v2022.5.1 というバージョンが出ていたので試しましたが、解消しませんでした。

幸い、v2021.12.1 のWindows版とMac版を手元に残してあったのでハンズオン自体はできるのですが、Burp側の仕様が変わったのだとしたら対応して頂けると嬉しいです。

**Comment by ankokuty** [comment]
@irok ありがとうございます。現象を確認しました。

**Comment by ankokuty** [comment]
@irok 修正してみたのですが、こちらでいかがでしょうか？問題なければリリースしようと思います。
[Hakoniwa BadStore.zip](https://github.com/ankokuty/HakoniwaBadStore/files/9029907/Hakoniwa.BadStore.zip)

**Comment by ankokuty** [comment]
確認ありがとうございます
